svelte-add/svelte-add

README.md

As discussed on discord, here is the bulma adder.

Add bulma adder

---

index.js
package.json

Closes: #14 
Don't ask! I don't know!
Deployed and testable here: https://www.npmjs.com/package/svelte-add-test
What I have basically done, is to copy the repo of [use-preset](https://github.com/preset/cli) and remove things one by one until I found this weird thing.
If you don't mind merging this because it's a dirty hack around something we don't know, I'm fine with it :smile:. But I'm done with this thing :joy:

🐛 fix: resolve pnpx bug (#14)

---

README.md

I made a CoffeeScript adder. How do I finish contributing it?
Tested with SvelteKit. I'm not sure if non-SvelteKit Vite works; I tried to leave the necessary code in there.
Special highlight: this adder makes an effort to preserve existing sveltePreprocess() options:
https://github.com/Leftium/coffeescript-adder/blob/cc0f2004cbc00c3224b0c095d01bd3a068f0eaef/preset.ts#L3-L14

Add CoffeeScript adder.

---

projects/svelte-add/README.md

Add a link to svelte-add-jest.

Add Jest adder link

---

projects/create-kit/cli.js

create-kit: add warning messages for failed adders

---

projects/svelte-add/adder-tools.js

🐛 fix: vite.config.js is created despite existing vite.config.ts #234

---

projects/svelte-add/index.js

🐛 fix: yields TODO: explain this error #228

---

projects/svelte-add/ast-tools.js

Fixes https://github.com/svelte-add/svelte-add/issues/237

⚡ feat: add tailwindcss config type comment

---

package.json
pnpm-lock.yaml
projects/app-initializer-tools/package.json
projects/create-kit/package.json
projects/create-vite/package.json
projects/svelte-add/package.json
projects/test/package.json

Resolves 
>  ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In projects\app-initializer-tools: No matching version found for svelte-add@workspace:2023.05.14-0.0 inside the workspace
inside project upon `pnpm install`

🐛 fix: package installation issues

---

package.json
pnpm-lock.yaml
projects/app-initializer-tools/package.json
projects/create-kit/package.json
projects/create-vite/package.json
projects/svelte-add/index.js
projects/svelte-add/package.json
projects/test/package.json
projects/test/tests/all-adders/get-public-adders-list-infos.js

SvelteLab/SvelteLab/issues/228

Add ability to fetch available adder names

---

generate-readmes.js
projects/svelte-add/README.md

📄 docs: re-generate readmes (issue-links, option syntax)

---

projects/svelte-add/adder-tools.js
projects/svelte-add/ast-tools.js
projects/svelte-add/package-versions.js

⚡ feat: switch to `vitePreprocess` (#244)

---

projects/svelte-add/index.js

Add full sass support

---

projects/svelte-add/README.md

Hi!
I've just added SASS in the list of built-in adders after my PR in (#303) has been approved.
I wanna thank all contributors for this amazing project that many (including me) will rely on in the future; Keep up the good work!

Added SASS to list of Integrated adders

---

projects/svelte-add/README.md

The Storybook integration is officially maintained by the Storybook team and is very high quality. I wouldn't say it's a work-in-progress at all

docs: update status of Storybook adder

---

projects/svelte-add/package-versions.js

Closes #318
Closes #319 
Closes #322 
Will run all tests. Introduced by this merge: https://github.com/svelte-add/tailwindcss/pull/65

fix: overwrite caused while installing prettier-plugin-tailwindcss

---

.changeset/wet-monkeys-count.md
packages/core/utils/dependencies.ts

fix: improve wording for installing dependencies

---

.changeset/rotten-spies-rescue.md
packages/core/adder/preconditions.ts

fix: only check dirty git repo precondition if in git repo

---

.changeset/tender-countries-grow.md
.github/workflows/preview-release.yml
packages/core/adder/preconditions.ts

fix: only print failed preconditions

---

adders/drizzle/config/adder.js
adders/drizzle/config/tests.js
adders/tailwindcss/config/adder.js
adders/threlte/config/adder.js
eslint.config.js
packages/ast-tooling/index.ts
packages/cli/index.ts
packages/cli/website.ts
packages/dev-utils/utils/generate-readme.ts
packages/tests/index.js

closes https://github.com/svelte-add/svelte-add/issues/404

fix: don't change capitalization of `moduleResolution`

---

.changeset/clever-dragons-sort.md
packages/core/adder/execute.ts
packages/core/adder/postconditions.ts
packages/core/adder/preconditions.ts

chore: improve welcome message

---

adders/drizzle/index.ts
packages/cli/package.json
pnpm-lock.yaml
scripts/get-deps-to-publish.js

chore(pkg-pr-new): include peer deps in dependents check

---

.changeset/ninety-kangaroos-hide.md
packages/clack-core/src/prompts/prompt.ts
packages/clack-prompts/index.ts
packages/core/utils/prompts.ts

closes #442
This alignment is definitely more pleasing to look at!
demo:

chore(CLI): adjust group header alignment

---

.changeset/flat-rice-suffer.md
packages/core/adder/options.ts

fix: validate cli adder names

---

.changeset/brave-dolphins-guess.md
adders/tailwindcss/config/adder.ts
packages/ast-tooling/index.ts
scripts/get-deps-to-publish.js

fixes #459
so the main broken part is that another `<slot>` element is added when one already exists in the layout. this fixes that, but the formatting is still sorta ugly if `prettier` isn't installed. 
to (somewhat) make it less horrific without prettier formatting, I've also updated `serializeSvelteFile` so that the script tag is added at the top, rather than at the bottom with `<style>` .
so rather than this:
<details>
```svelte
<div class="app">
<Header></Header>
<main>
<slot></slot>
</main>
<footer>
<p>
visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to learn SvelteKit
</p>
</footer>
</div>
<script>import "../app.css";
import Header from "./Header.svelte";
import "./styles.css";</script><style>
.app {
display: flex;
flex-direction: column;
min-height: 100vh;
}
main {
flex: …
```

fix: only add a slot element if it's missing

---

.changeset/rude-poets-film.md
packages/core/files/processors.ts

fix: correctly parse newly created json files

---

.changeset/spicy-bobcats-look.md
packages/core/files/utils.ts

chore: add new lines at the end of files

---

.changeset/great-cars-float.md
.changeset/tender-fans-brake.md
adders/tailwindcss/config/adder.ts
packages/core/adder/config.ts
packages/core/adder/options.ts

feat: support adder aliases

---

.changeset/mighty-gifts-sing.md

This changeset was forgotten as part of #502

fix: add missing changeset

---

.changeset/cuddly-planets-turn.md
packages/website/src/routes/adder/[adder]/+page.svelte

Discovered in the last [dev vlog](https://www.youtube.com/watch?v=uqnbA1xDe8k)

fix: undefined on website

---

.changeset/eleven-ways-fry.md
adders/eslint/config/adder.ts
eslint.config.js
package.json
pnpm-lock.yaml

did I do the changeset correctly by including only the one package?

chore: upgrade to typescript-eslint v8 final

---

.changeset/dull-games-deliver.md
adders/tailwindcss/config/adder.ts

it still works just fine without it

fix: don't need to install postcss with tailwindcss

---

.changeset/wise-ravens-exercise.md
packages/core/package.json
packages/core/utils/dependencies.ts
pnpm-lock.yaml

https://npmgraph.js.org/?q=preferred-pm - 24 dependencies
https://npmgraph.js.org/?q=package-manager-detector - 0 dependencies

chore: replace preferred-pm with package-manager-detector

---

.changeset/brown-beans-compare.md
packages/core/utils/dependencies.ts
packages/testing-library/utils/test-cases.ts

just noticed this, but also mainly wanted to test CI

fix: execute adders in order
