- projects/svelte-add/README.md
Closes https://github.com/svelte-add/svelte-add/issues/133
It's not technically built using the `svelte-add` infrastructure, but it works in just the same way for users where it takes a project you've created and then augments it with the Storybook functionality, so it's probably worth documenting as there's no point in duplicating the functionality
> Add link to Storybook adder

- projects/svelte-add/ast-io.js
Fixes #195.
Fixes the issue with lowercasing the "Header" tag, when i.e. the scss adder is added to a clean project, whicht was created with the `"demo": yes` option. 
I can confirm that after this change the text remains upper case. 
The parser documentation notes that we should use `xmlMode` of the parser. But that doesn't work out for us, because we rely on special handling of i.e. the script tag. 
With the current combination everything seems to work out great, as far as I can tell.
> Fixes #195: Don't auto lowercase html tags

- projects/svelte-add/cli.js
- projects/svelte-add/index.js
Based on #249 
* Fix exception when detection failed, because one of the checked package managers was not installed on the system
* Fix wrong displayed command, if no package manager was selected for installation in interactive mode.
> ⚡ feat: improve package manager detection

- pnpm-lock.yaml
- projects/svelte-add/ast-io.js
- projects/svelte-add/package.json
I'm getting a big ugly warning when running `svelte-add`. I expect this should fix it
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
YOUR TYPESCRIPT VERSION: 5.2.2
Please only submit bug reports when using the officially supported version.
=============
```
The types for the package were moved from a `types` field directly in the `package.json` to living within the `exports`. I'm not sure why that's not working. I guess there might need to be some change to the `tsconfig.json` file in this project, but don't really have time to track it down now as I'm in the middle of recording a …
> chore: bump @typescript-eslint/typescript-estree

- projects/svelte-add/adder-tools.js
As of sveltekit v2 `vitePreprocess` is no longer exported from `@sveltejs/kit/vite`, So `vitePreprocess` always is imported from `@sveltejs/vite-plugin-svelte`.
This fixes the bug where `vitePreprocess` is imported 2 times
> fix: import `vitePreprocess` from `vite-plugin-svelte` in sveltekit

- projects/svelte-add/index.js
Hi there!
It looks like folks are trying to use `svelte-add` with Bun, but there's an error right now: https://github.com/oven-sh/bun/issues/9983
```js
153 | 		}
154 | 	}
155 | 
156 | 	if (install) await installDependencies({ packageManager, platform: environment.platform, projectDirectory });
157 | 	else {
158 | 		const [command, commandArgs] = packageManagers[packageManager].install;
^
TypeError: undefined is not an object (evaluating 'packageManagers[packageManager].install')
at /private/tmp/bunx-501-svelte-add@latest/node_modules/svelte-add/cli.js:158:34
```
The root cause appears to be that the `detect-package-manager` is correctly detecting `bun`, but in `svelte-add/index.js`, Bun is not defined as a possible package manager. This PR fixes that.
> Support `bun` as a package manager

- .changeset/purple-ravens-wink.md
- packages/ast-tooling/index.ts
- packages/ast-tooling/package.json
- packages/core/adder/execute.ts
- packages/core/index.ts
- packages/core/utils/common.ts
- packages/core/utils/create-project.ts
- packages/core/utils/workspace.ts
- packages/testing-library/utils/test.ts
- pnpm-lock.yaml
Similar to #344, this change will preserve the JSON indentation if no prettier installation / config could be determined. 
As an improvement over #344 this change will keep the user chosen indentation (2 spaces, 4 spaces, tabs, etc.) and not convert everything to tabs.
> fix: preserve json indentation 

- .changeset/bright-cooks-push.md
- .changeset/heavy-beers-sell.md
- adders/tailwindcss/config/adder.js
- packages/core/files/processors.ts
Here's the current output of the `app.css` file for the Tailwind adder:
```css
@tailwind utilities;
@tailwind components;
@tailwind base
```
There are 2 issues that can be found above:
- The order of the `@tailwind` directives is upside-down. Instead, it should be: `base`, `components`, `utilities`.
- `@tailwind base` is missing the semicolon at the end. While it _does work_ without it in practice, it simply looks nicer and is less confusing with it always being added.
This PR addresses both.
> fix: corrects the `@tailwind` directive order and adds optional semicolon in `app.css`

- .changeset/cool-socks-punch.md
- .changeset/ten-carrots-rescue.md
- adders/bootstrap/config/adder.js
- adders/bulma/config/adder.js
- adders/tailwindcss/config/adder.js
For the tailwind adder, `+layout.js` was being installed instead of the needed `+layout.svelte` file.
> fix: install the correct `+layout.svelte` file for Tailwind adder

- .changeset/new-pugs-appear.md
- adders/bootstrap/config/adder.js
- adders/bulma/config/adder.js
- adders/tailwindcss/config/adder.js
Generated `+layout.svelte` files were missing their corresponding `slot` elements. Not quite sure how I missed this during the fix of #343 🤦‍♂️
> fix: add slot element for layouts

- .changeset/funny-bags-suffer.md
- .changeset/red-jars-press.md
- adders/bootstrap/config/adder.js
- package.json
- packages/ast-manipulation/css/index.ts
- packages/ast-manipulation/js/array.ts
- packages/ast-manipulation/js/exports.ts
- packages/ast-manipulation/js/imports.ts
- packages/ast-manipulation/js/object.ts
- packages/ast-manipulation/js/variables.ts
- packages/ast-tooling/index.ts
- packages/cli/index.ts
- packages/core/adder/execute.ts
- packages/core/adder/options.ts
- packages/core/files/utils.ts
- packages/core/utils/common.ts
- packages/core/utils/create-project.ts
- packages/core/utils/dependencies.ts
- packages/core/utils/prompts.ts
- packages/core/utils/workspace.ts
- packages/dev-utils/utils/update-packages.js
- packages/testing-library/utils/adder.ts
- packages/testing-library/utils/dev-server.ts
- packages/testing-library/utils/test-cases.ts
- packages/testing-library/utils/test.ts
- pnpm-lock.yaml
- rollup.config.js
- tsconfig.json
closes #351
closes #355
This PR enables TS's [strict mode](https://www.typescriptlang.org/tsconfig/#strict) and fixes several spots where the types were failing. I also took the liberty of fixing #355 as the logic had to be adjusted anyway to better satisfy the new type requirements.
Additional notes for this PR can be seen below 👇
> chore: Enable `strict` mode and adders install dependencies directly

- .changeset/nasty-pants-perform.md
- .changeset/slimy-comics-know.md
- adders/tailwindcss/config/adder.js
- packages/ast-manipulation/js/common.ts
- packages/ast-manipulation/js/imports.ts
closes #348 
Went with the `as Config` route as it was the easiest to implement with relatively low risk of causing side-effects down the line.
> chore: correctly type annotate `tailwind.config.ts`'s config when using typescript

- .changeset/smooth-pens-repair.md
- packages/core/adder/execute.ts
- packages/core/adder/preconditions.ts
- packages/core/utils/common.ts
Closes #363
Adds a new global precondition checking if the working directory is a git repository and contians uncomitted changes. If that's the case the precondition will fail.
As with all other preconditions, this check can be disabled with `--skip-preconditions`
> feat: display warning if dirty git workspace

- .changeset/curly-peaches-do.md
- packages/core/adder/execute.ts
- packages/core/adder/options.ts
- packages/core/utils/dependencies.ts
- packages/dev-utils/utils/generate-readme.ts
Closes #350
This PR adds the `--default` flag as a shorthand to install the default adder options for **missing options**.
For example, say that we have 2 tailwind options `typography` and `forms` (assume both have their defaults set to `false`). If we were to run the command like so:
```bash
@svelte-add/tailwindcss --default --typography
```
the `typography` plugin will still be added as it was manually specified, but the `forms` plugin will not.
> feat: add `--default` flag

- adders/bootstrap/config/tests.js
- adders/routify/config/tests.js
- adders/storybook/config/adder.js
- package.json
- packages/core/adder/config.ts
- packages/testing-library/package.json
- packages/testing-library/utils/browser-control.ts
- packages/testing-library/utils/test.ts
- pnpm-lock.yaml
- rollup.config.js
With a little bit of finagling, the migration to playwright was relatively straightforward (compared to my last attempt, where I was trying to also integrate vitest as well). 
I'll be leaving some comments attached for reasons behind specific changes.
> chore: replace `puppeteer` for `playwright`

- .changeset/silent-students-poke.md
- adders/storybook/config/adder.js
Storybook feels out-of-place in the styling category to me since it's not a CSS framework like the others and does so much more than just help you with styling. 
From their homepage:
Storybook is a frontend workshop for building UI components and pages in isolation. Thousands of teams use it for UI development, testing, and documentation.
> fix: move storybook from styling category to tools category

- .changeset/slimy-singers-shave.md
- adders/routify/config/tests.js
- packages/core/adder/config.ts
- packages/core/adder/execute.ts
- packages/core/adder/preconditions.ts
- packages/core/internal.ts
- packages/core/utils/create-project.ts
- packages/testing-library/utils/test.ts
Overall, this PR tries to avoid that users get the possibility to apply an adder for an unsupported environment. Each adder can define the supported environments in its adder config.
Closes #394 
Closes #387
There are a few cases that we need to consider in order to ensure this requirement.
```sh
npx svelte-add
```
This will detect a project in the cwd or ask the user to create a project. After that it will display all categories with the appropriate adders. Up to this point a project has been detected for sure, so we can just hide the invalid combinations (i.e. routify, if kit project)
```sh
npx @svelte-add/routify
```
This will detect a project in the cwd or ask the user to create a project. If creating a project, the user is unable to create a kit project, as that option is hidden, and …
> fix: avoid adding adders to unsupported project types

- .github/workflows/preview-release.yml
- package.json
- pnpm-lock.yaml
this PR also removes `pkg-pr-new` as a dependency and instead executes it remotely with `pnpm dlx pkg-pr-new@0.0`, which pins it to the latest patch release
> chore: have `pkg.pr.new` publish when a PR is "ready for review"

- .changeset/wild-shoes-argue.md
- packages/ast-manipulation/html/index.ts
- packages/ast-manipulation/index.ts
- packages/ast-manipulation/js/array.ts
- packages/ast-manipulation/js/common.ts
- packages/ast-manipulation/js/exports.ts
- packages/ast-manipulation/js/function.ts
- packages/ast-manipulation/js/imports.ts
- packages/ast-manipulation/js/index.ts
- packages/ast-manipulation/js/object.ts
- packages/ast-manipulation/js/variables.ts
- packages/ast-tooling/index.ts
- packages/core/adder/config.ts
- packages/core/adder/execute.ts
- packages/core/adder/options.ts
- packages/core/adder/postconditions.ts
- packages/core/adder/preconditions.ts
- packages/core/files/processors.ts
- packages/core/internal.ts
- packages/dev-utils/utils/generate-readme.ts
- packages/dev-utils/utils/update-dependencies.ts
- packages/dev-utils/utils/update-packages.ts
- packages/testing-library/index.ts
- packages/testing-library/utils/dev-server.ts
- packages/testing-library/utils/test-cases.ts
- packages/testing-library/utils/workspace.ts
- tsconfig.json
This PR enables [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax) which will mainly be helpful for us in catching cases where we're not properly importing and exporting types
> chore: fix all type imports and exports

- .changeset/friendly-snakes-drop.md
- adders/bulma/config/adder.ts
- adders/tailwindcss/config/adder.ts
While testing #421 I saw that some adders had dot's at the end of the description and some did not. This unifies the description to be without a dot as this looks better in my opinion
> fix: adder punctuation

- .changeset/curly-parrots-taste.md
- packages/cli/README.md
- packages/core/adder/options.ts
- packages/website/src/lib/Configurator.svelte
As suggested in #420 we are able to omit the `--adder` flag. This simplifies usage and makes the command shorter to remember.
You can now use
```
pnpm dlx svelte-add@latest tailwindcss bootstrap
```
instead of 
```
pnpm dlx svelte-add@latest --adder tailwindcss bootstrap
```
> feat: simplify cli usage `pnpm dlx svelte-add tailwindcss`

- packages/cli/package.json
- pnpm-lock.yaml
Should fix the major version bump in #430
> chore: `svelte-add` should not be a peer dep of itself

- .changeset/gorgeous-crabs-camp.md
- .changeset/moody-pumas-do.md
- adders/bootstrap/config/adder.ts
- adders/drizzle/config/adder.ts
- packages/core/adder/config.ts
- packages/core/adder/execute.ts
- packages/core/adder/nextSteps.ts
Closes #390 
Initial implementation to gather feedback.
This is basically implemented, and you can try it out with the preview release that will be published. 
If applying multiple adders (`pnpm dlx svelte-add`) it will always print the display name of the adder and the link to the documentation. If running for one adder alone (`pnpm dlx @svelte-add/bootstrap`) it will skip the name and only print the docs link. Additionally, each adder can provide its custom text that will be displayed below the docs link (currently only implemented for the bootstrap adder).
Here are a few questions for discussion:
1. Should we always print the docs link for each adder?
2. Do the adders need any context (parameters) to generate the next steps? Would the selected options and the cwd be useful?
3. Should …
> feat: display next steps after running the adders

- .changeset/cyan-moose-beg.md
- packages/core/adder/execute.ts
this will need a changeset, but I didn't know if you wanted to add it as patch or minor, so feel free to add one with the bot
> feat: display website documentation url in hint

- .changeset/rude-bananas-mix.md
- CONTRIBUTING.md
- adders/bootstrap/config/adder.ts
- adders/bulma/config/adder.ts
- adders/drizzle/config/adder.ts
- adders/mdsvex/config/adder.ts
- adders/routify/config/adder.ts
- adders/storybook/config/adder.ts
- adders/tailwindcss/config/adder.ts
- packages/cli/index.ts
- packages/cli/package.json
- packages/cli/website.ts
- packages/config/README.md
- packages/config/adders/community.ts
- packages/config/adders/official.ts
- packages/config/categories.ts
- packages/config/index.ts
- packages/config/package.json
- packages/core/adder/config.ts
- packages/core/adder/execute.ts
- packages/core/adder/nextSteps.ts
- packages/core/index.ts
- packages/core/internal.ts
- packages/core/utils/common.ts
- packages/testing-library/utils/test-cases.ts
- packages/website/package.json
- packages/website/src/lib/adder.ts
- packages/website/src/routes/categories/[category]/+page.server.ts
- pnpm-lock.yaml
- rollup.config.js
This prepares `svelte-add` to provide a non-alphabetical order of adders in the cli and the website. Additionally, this prepares a few types and files to support community adders, but no functionality at this point.
Notable changes
* There is now a package `@svelte-add/config` which provides the following
* A list of categories extracted from `@svelte-add/core` (core was never really using the categories, only the cli and the website)
* A mapping from categories to adders present in that category. The order the adders are written in this config, will be the order they will be displayed in the cli and on the website.
* A list of community adders (not in use at this point, but I already added them since I was already generating this new package)
* Changed responsibilities for handling of …
> feat: custom ordered adders

- .changeset/empty-pillows-bathe.md
- .changeset/odd-actors-buy.md
- packages/cli/index.ts
- packages/testing-library/package.json
- pnpm-lock.yaml
Closes #432 
To reproduce the issue
```
pnpm dlx svelte-add@2.2.1
```
create a new svelte project (js  / ts does not matter). You will see the empty Database category.
After this fix, this will not happen anymore
> fix: do not display empty categories in cli

- .changeset/cyan-dogs-give.md
- .changeset/quiet-toes-look.md
- adders/drizzle/config/adder.ts
- packages/core/index.ts
- packages/core/package.json
- pnpm-lock.yaml
Closes #418 
The original issue is only reproducible for me, when creating a new project via our cli, outside the monorepo. The `docker-compose.yml` was intended way to much in that case, and contained a new line that shouldn't be there.
This does not happen on pre-existing projects, as we try to run the locally installed prettier instance and try to format that file.
> fix: `docker-compose.yml` intendation

- .changeset/selfish-dots-yell.md
- .changeset/wise-coins-hammer.md
- adders/drizzle/config/tests.ts
- packages/ast-tooling/index.ts
- packages/core/adder/execute.ts
- packages/core/files/processors.ts
- packages/core/files/utils.ts
- packages/core/package.json
- packages/core/utils/dependencies.ts
- pnpm-lock.yaml
`prettier` is [ginormous](https://npmgraph.js.org/?q=svelte-add#select=exact%3Aprettier%403.3.2&sizing=) and is the largest dependency that users have to download every time they call any of our adders. 
Rather than having it as a direct dependency and using it's api in code, we can check if `prettier` is installed in their project and run the formatter via its CLI after all of the adders have executed and after dependency installations have occurred (covers the case of if `node_modules` isn't installed yet).
> chore: remove `prettier` as a dependency

- .github/workflows/ci.yml
- .github/workflows/preview-release.yml
At the moment, most of our workflows are [running in Node16](https://github.com/svelte-add/svelte-add/actions/runs/9725826885) (except our changesets workflow) as we're using older versions of actions. This PR upgrades them all so that may run in Node20.
> chore: upgrade all workflow action versions  

- .github/workflows/changesets.yml
- package.json
scripts `pnpm utils:readmes && pnpm utils:packages` no longer exists and is causing the [changesets workflow to fail](https://github.com/svelte-add/svelte-add/actions/runs/9725879570).
`ci:version` is also no longer needed since we don't have to do any additional processing before versioning the packages. the changesets action runs `changesets version` by default, so we can safely remove it.
> chore: fix changesets

- package.json
- packages/ast-manipulation/js/exports.ts
- packages/clack-core/package.json
- packages/clack-prompts/package.json
- packages/website/package.json
- pnpm-lock.yaml
This PR mainly upgrades the deps in the repo root.
Some notable changes:
- noticed the root `package.json` wasn't set to `private`
- upgrades `typescript` to `5.5.2` and `typescript-eslint` to the respective compatible version
- upgrades `changesets `to `2.27.6` which removes a considerable amount of their dependencies
- upgraded `picomatch` to match what we're using in `@svelte-add/core`
> chore: general dependency updates

- .changeset/late-zoos-decide.md
- packages/ast-tooling/index.ts
- packages/core/adder/execute.ts
closes #457
I'm not 100% sure that this is the right solution, but I'll point out my concerns below:
> fix: alphabetize `dependencies` and `devDependencies`

- .changeset/eleven-lamps-attack.md
- packages/ast-manipulation/js/exports.ts
- packages/ast-manipulation/js/object.ts
- packages/core/adder/execute.ts
- packages/core/utils/workspace.ts
fixes #473 
The CLI will fail to startup if the variable for the svelte config object isn't the first declared variable.
for example, this is OK:
```js
import adapter from "@sveltejs/adapter-auto";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
/** @type {import('@sveltejs/kit').Config} */
const config = {
// Consult https://kit.svelte.dev/docs/integrations#preprocessors
// for more information about preprocessors
preprocess: [vitePreprocess()],
kit: {
// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
// See https://kit.svelte.dev/docs/adapters for more information about adapters.
adapter: adapter()
},
};
export …
```
> fix: improve svelte config parser

- .changeset/happy-apples-move.md
- .changeset/slimy-clocks-cough.md
- adders/drizzle/config/adder.ts
- adders/drizzle/config/tests.ts
- packages/ast-manipulation/js/common.ts
- packages/ast-manipulation/js/object.ts
- packages/ast-manipulation/package.json
- pnpm-lock.yaml
While working on #467, I noticed that the robustness of the drizzle adder's config modifications could be improved. Running the adder again and changing the DB type wouldn't result in updates to the user's `drizzle.config.ts` (i.e. updating the `driver` field from `sqlite` to `mysql`). Now, if the adder is ran again with a different DB selected, the drizzle config will update accordingly.
> fix: improve robustness of `drizzle` adder

- .changeset/thirty-countries-kiss.md
- packages/core/files/processors.ts
Identified based on the issue detailed in #477. The main point is to include the file name for better debugging. This may also allow the user to make his own adjustments before opening an issue
Before this change: 
```
└  Identifier 'text' has already been declared. (2:22)
SyntaxError: Identifier 'text' has already been declared. (2:22)
at constructor (file:///D:/dev/web/svelte-add/packages/ast-tooling/build/index.js:9480:20)
at V8IntrinsicMixin.raise (file:///D:/dev/web/svelte-add/packages/ast-tooling/build/index.js:12362:20)
at TypeScriptScopeHandler.declareName (file:///D:/dev/web/svelte-add/packages/ast-tooling/build/index.js:16012:22)
at V8IntrinsicMixin.declareNameFromIdentifier (file:///D:/dev/web/svelte-add/packages/ast-tooling/build/index.js:16438:17)
at …
```
> fix: better file error handling

- .changeset/silent-turkeys-sell.md
- packages/core/utils/dependencies.ts
closes https://github.com/svelte-add/svelte-add/issues/479
> fix: correct typo in package manager prompt

- .changeset/cyan-kings-call.md
- CONTRIBUTING.md
- packages/website/src/lib/Configurator.svelte
Follow-up on #489 
Right now, when I click an adder option from the docs (`+`), it configures the old syntax of `@svelte-add/{something}`
I didn't test locally, unfortunately, because the local dev server threw an error:
```
[plugin:vite:import-analysis] Failed to resolve entry for package "@svelte-add/config". The package may have incorrect main/module/exports specified in its package.json.
``` 
So please feel free to close if this is wrong.
> docs: add correct adder script

- .changeset/funny-glasses-pump.md
- adders/tailwindcss/config/adder.ts
Addresses one of the issues from #482
Replaces the tailwind directives:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
for imports:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
This was done for better compatibility when the adder is used in preexisting projects that have `@import` rules already applied. See https://github.com/svelte-add/svelte-add/issues/482#issuecomment-2239733898 for more details.
> fix: Replace `@tailwind` directives for `@import`

- .changeset/ninety-squids-grow.md
- .changeset/old-hornets-design.md
- .changeset/soft-cars-end.md
- adders/tailwindcss/config/adder.ts
- packages/ast-manipulation/css/index.ts
- packages/ast-tooling/index.ts
Note: this PR should be merged after #492 
Fixes #482
`@import` rules will now be added with the correct spacing:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "@fontsource/fira-mono";
:root {
...
```
> fix(tailwind): ensure `@import` rules are single spaced when added

- .changeset/breezy-knives-crash.md
- .changeset/two-avocados-brush.md
- packages/ast-manipulation/package.json
- packages/cli/package.json
- packages/dev-utils/package.json
- packages/testing-library/package.json
- packages/tests/package.json
- packages/website/package.json
- pnpm-lock.yaml
At the moment, trying to run older versions of `svelte-add` is kind of broken.
For instance, running:
```bash
pnpx svelte-add@2.3.0
```
will break due to `prettier` being added to the config when it doesn't exist locally in this package yet (it was added in `2.3.7`). I suspect this is partially the reason why #457 is broken in some cases. 
This is happening because range specifiers are being using when our workspace packages are referencing each other with `workspace:^`. Instead, we should be using `workspace:*` to specify exact versions on publish (this would effectively be equivalent to us bundling everything into a single package, but due to build times with AST tooling, it's not viable).
When publishing with `workspace:^`, workspace deps will have their versions set to `^2.3.5`. With …
> chore: workspace deps should specify exact versions on publish

- .changeset/sweet-bees-happen.md
- adders/tailwindcss/config/adder.ts
Noticed when running the tailwind adder, `prettier-plugin-tailwindcss` would continously be appended to the plugin array in `.prettierrc`, even when it already exists. This PR fixes that.
> fix(tailwind): Only insert `prettier-plugin-tailwindcss` to `.prettierrc` if it doesn't exist

- .changeset/slow-chairs-tell.md
- adders/mdsvex/config/adder.ts
- packages/ast-manipulation/js/common.ts
- packages/ast-manipulation/package.json
- packages/ast-tooling/index.ts
- pnpm-lock.yaml
fixes #464
locations need to be stripped in order for node comparisons to work properly, see: https://github.com/svelte-add/svelte-add/pull/379#discussion_r1638361267
rather than stripping the ast locations from the original tree, we'll now create a clone of the tree and strip it from there during comparisons.
---
notable observation: it doesn't seem to be perfect either, but I'm not sure why. 
for instance, here's the before:
and here's the after:
however, if I format it using tabs and run the adder again, the tabs are entirely preserved... so I'm not quite sure what's going on there 😅
> fix: preserve formatting for JS files

- .changeset/rich-clouds-smash.md
https://github.com/svelte-add/svelte-add/pull/393 still uses the `@next` tag
> docs: update changelog item description

- .changeset/thirty-tools-compete.md
fixes #503 
Because #498 didn't publish properly, the release had to be manually published (although I'm unsure which of those packages were actually published). 
This PR adds a changeset to all public packages to ensure their latest code changes are published.
> chore: trigger releases

- .changeset/angry-ducks-grin.md
- .changeset/neat-ravens-peel.md
- packages/core/files/utils.ts
- packages/core/utils/workspace.ts
- packages/testing-library/package.json
- pnpm-lock.yaml
In https://github.com/sveltejs/kit/pull/12453 `tslib` got removed, which broke our typescript detection. If we now detect a `tsconfig.json` or a `vite.config.json` in the current or any of the upwards directories, we assume that we have typescript project.
> fix: typescript detection

- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
Make it easier to remember how to test an adder. 
Instead of using `node .\packages\cli\build\index.js` you can now use `pnpm svelte-add`
> chore: add `svelte-add` script for development

- .changeset/tender-baboons-raise.md
- adders/playwright/config/adder.ts
Didn't realize playwright exported their own `defineConfig` helper function for configs. Using this instead will allow the JS and TS versions of the config be identical.
> chore: use `defineConfig` for playwright adder

- .changeset/clever-moons-buy.md
- adders/storybook/config/tests.ts
- packages/testing-library/index.ts
- packages/testing-library/utils/browser-control.ts
- packages/testing-library/utils/test-cases.ts
- packages/testing-library/utils/workspace.ts
This PR is more of an experiment to see if this can speedup our current test suite. 
Rather than having each test case be it's own individual project, we'll just setup the `.outputs` directory as an pnpm workspace. Additionally, instead of running `pnpm install` for each test case (which takes a notable amount of time, even when pnpm doesn't have to download anything), we'll just run the install command once at the root after executing all of the adders. 
This change has a pretty nice impact locally, so I'm interested in seeing the effects in CI.
Also includes:
- Using a single browser instance with new pages rather than destroying and creating a new browser on every test case
- Fixed storybook test so that it can run asynchronously (the main issue was that the same port `6006` was being …
> chore: Speed up tests

- .changeset/gorgeous-seahorses-repeat.md
- .changeset/six-parrots-tan.md
- adders/eslint/config/tests.ts
- adders/playwright/config/tests.ts
- adders/prettier/config/tests.ts
- adders/storybook/config/adder.ts
- adders/storybook/config/tests.ts
- adders/vitest/config/tests.ts
- packages/testing-library/utils/test-cases.ts
- packages/testing-library/utils/workspace.ts
Temporarily pinning the storybook version until https://github.com/storybookjs/storybook/issues/28819 is resolved.
I've also added a small tweak to make the tests run just [a tiny bit faster too](https://github.com/svelte-add/svelte-add/actions/runs/10291840325/job/28484994433) **(3m 43s)**
> fix: pin `storybook` version and faster testing

- .changeset/cuddly-tips-trade.md
- .github/workflows/changesets.yml
- packages/ast-manipulation/package.json
- packages/ast-tooling/package.json
- packages/cli/package.json
- packages/config/package.json
- packages/core/package.json
- packages/testing-library/package.json
I tested this on SvelteKit already. Now we have a nice little green checkmark next to the version on npm
> chore: publish package provenance info
